development:
  adapter: postgresql
  encoding: unicode
  database: tsubuyaki_development
  pool: 5
  username: kosuke
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tsubuyaki_development
  pool: 5
  username: kosuke
  password:
